import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { Lexend_Deca } from 'next/font/google';
import { AuthProvider } from "@/lib/authContext";

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  weight: ['400'], // Adjust weight if needed
  variable: '--font-lexend-deca', // CSS variable for use in Tailwind or styles
});


export const metadata = {
  title: "Taitaja Tietotesti",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={lexendDeca.variable}>
      <body>
      <AuthProvider>
        <Navbar />
        {children}
        <Footer />
      </AuthProvider>
      </body>
    </html>
  );
}
